import Head from "next/head";
import {useRouter} from "next/router";
import {formatRoute} from "../../utils/routeFormatter";

export const Header = () => {
  const {route} = useRouter();
  const formattedRoute = formatRoute(route);

  return (
    <Head>
      <title>
        {formattedRoute === "/" ? "Home" : formattedRoute} - AustinOS
      </title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};
